function towers_select_labels()
%TOWERS_SELECT_LABELS Select object labels
%
% -------------
% DEFINITION
% -------------
% Each object in the geometry file is given a attributed a textual
% label (string) in the second position of geometry line, after the object
% type definition. Labels are indexed with integers, increasing
% monotonically from zero.
%
% Example: 
% The first "0" in the first line dfines the object as a "Page" and the
% second "0" as "Unlabeled"; while in the second line we have a "Text"
% object ("1") labeled "Headline" ("1").
% ...
% 			[0,0,0,0,1555.12,0,1555.12,1967.87,0,1967.87],
%			[1,1,124,8,1430,8,1430,311,124,311],
% ...
% 	"metadata":
% 	{
% 		"filename":"17660711_01_028.pdf",
% 		"url":"file:///Volumes/NB74/ZFZ_1766/17660711_01_028/17660711_01_028.pdf",
% 		"volume":[0.0000, 1555.1200, 1967.8700, 0.0000, 4],
% 		"counts":[4, 36, 1, 0, 0],
% 		"objects":[[0,"Pages"],[1,"Text"],[2,"Images"],[3,"Graphics"],[4,"Fonts"]],
% 		"labels":[[0,"Unlabeled"],[1,"Headline"],[2,"Illustration"],[3,"Publishing_Stmt"],[4,"Textblock"]],
% 	}
% ...
%
% -------------
% CREDITS
% -------------
% Vlad Atanasiu
% atanasiu@alum.mit.edu
% http://alum.mit.edu/www/atanasiu/
% 
% -------------
% LOG
% -------------
% 2018.10.01 - creation


% get object labels list
handles = guihandles(gcf);
hFigureMain = handles.figureMain;
ui = getappdata(hFigureMain,'ui');
objLabels = getappdata(hFigureMain,'labels');

% build GUI
ui.pushbuttonLabelsCancelY = ui.PadXY;
ui.pushbuttonLabelsCancelX = ui.PadXY;
ui.pushbuttonLabelsOKY = ui.PadXY;
ui.pushbuttonLabelsOKX = ui.PadXY*2 + ui.ButtonW;
ui.listboxLabelsY = ui.pushbuttonLabelsOKY + ui.ButtonH + ui.PadXY;
ui.listboxLabelsW = ui.ButtonW*2 + ui.PadXY;
ui.listboxLabelsH = 300;
ui.radiobuttonSelectionSomeY = ui.listboxLabelsY + ui.listboxLabelsH + ui.PadXY;
ui.hRadiobuttonSelectionNoneY = ui.radiobuttonSelectionSomeY + ui.ButtonH + ui.PadXY;

% get main figure location in characters
ui.FigMainX = hFigureMain.Position(1);
ui.FigMainY = hFigureMain.Position(2) + floor(hFigureMain.Position(4)/2);
ui.FigMainW = hFigureMain.Position(3);
ui.FigMainH = hFigureMain.Position(4);

ui.FigX = ui.FigMainX + floor(ui.FigMainW/2) - floor(ui.FigW/2);
ui.FigY = ui.FigMainY + floor(ui.FigMainH/2) - floor(ui.FigH/2);
ui.FigW = ui.listboxLabelsW + ui.PadXY*2;
ui.FigH = ui.hRadiobuttonSelectionNoneY + ui.ButtonH + ui.PadXY;


% interface objects
hFigureLabels = figure(...
    'Tag','figureLabels',...
    'Name','Labels Selector',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Toolbar','none',...
	'Units','pixels',...
    'Position',[ui.FigX, ui.FigY, ui.FigW, ui.FigH],...
    'Visible','on');

% lists
hRadiobuttonSelectionNone = uicontrol(...
    'Tag','radiobuttonSelectionNone',...
    'String','No Selection',...
    'Parent',hFigureLabels,...
    'Callback',@radiobuttonSelectionNone_Callback,...
    'Enable','on',...
    'FontSize',10,...
    'Units','pixels',...
    'Position',[ui.PadXY, ui.hRadiobuttonSelectionNoneY, ui.ButtonW, ui.ButtonH],...
    'Style','radiobutton',...
    'Value',1,...
    'Visible','on');

hRadiobuttonSelectionSome = uicontrol(...
    'Tag','radiobuttonSelectionSome',...
    'String','Selected Labels:',...
    'Parent',hFigureLabels,...
    'Callback',@radiobuttonSelectionSome_Callback,...
    'Enable','on',...
    'FontSize',10,...
    'Units','pixels',...
    'Position',[ui.PadXY, ui.radiobuttonSelectionSomeY, ui.ButtonW, ui.ButtonH],...
    'Style','radiobutton',...
    'Value',0,...
    'Visible','on');

hListboxLabels = uicontrol(...
    'Tag','listboxLabels',...
    'Parent',hFigureLabels,...
    'Callback',@listboxLabels_Callback,...
    'Enable','on',...
    'FontName','FixedWidth',...
    'FontSize',10,...
    'Units','pixels',...
    'Position',[ui.PadXY ui.listboxLabelsY ui.listboxLabelsW ui.listboxLabelsH],...
    'String',objLabels.list,...
    'Style','listbox',...
    'Max',2,...
    'Min',0,...
    'KeyPressFcn',@listboxLabels_Callback); %#ok<NASGU>

% buttons
hPushbuttonLabelsCancel = uicontrol(...
    'Tag','pushbuttonLabelsCancel',...
    'String','Cancel',...
    'Parent',hFigureLabels,...
    'Callback',@pushbuttonLabelsCancel_Callback,...
    'Enable','on',...
    'FontSize',10,...
    'Units','pixels',...
    'Position',[ui.PadXY ui.PadXY ui.ButtonW ui.ButtonH],...
    'Style','pushbutton'); %#ok<NASGU>

hPushbuttonLabelsOK = uicontrol(...
    'Tag','pushbuttonLabelsOK',...
    'String','OK',...
    'Parent',hFigureLabels,...
    'Callback',{@pushbuttonLabelsOK_Callback, hFigureMain, objLabels},...
    'Enable','on',...
    'FontSize',10,...
    'Units','pixels',...
    'Position',[ui.pushbuttonLabelsOKX ui.PadXY ui.ButtonW ui.ButtonH],...
    'Style','pushbutton'); %#ok<NASGU>

% finish
setappdata(hFigureMain,'labels',objLabels)


% no selection radiobutton
function radiobuttonSelectionNone_Callback(hObject, ~)

% deactivation of opposite choice controls
handles = guihandles(hObject);
handles.radiobuttonSelectionNone.Value = 1;
handles.radiobuttonSelectionSome.Value = 0;


% some selection radiobutton
function radiobuttonSelectionSome_Callback(hObject, ~)

% deactivation of opposite choice controls
handles = guihandles(hObject);
handles.radiobuttonSelectionNone.Value = 0;
handles.radiobuttonSelectionSome.Value = 1;


% selection operated
function listboxLabels_Callback(hObject, ~)

% deactivation of opposite choice controls
handles = guihandles(hObject);
handles.radiobuttonSelectionNone.Value = 0;
handles.radiobuttonSelectionSome.Value = 1;


% cancel font selection process
function pushbuttonLabelsCancel_Callback(~, ~)
close gcf


% ok: show objects with selected labels
function pushbuttonLabelsOK_Callback(~, ~, hFigureMain, objLabels)

% get selection status
handles = guihandles(gcf);
if handles.radiobuttonSelectionNone.Value == 1
    objLabels.selection = "";
else
    idx = handles.listboxLabels.Value;
    objLabels.selection = rot90(cellstr(handles.listboxLabels.String(idx)));
end

% close font selection figure so that we can draw on the main figure
close gcf

% save selection to figure
setappdata(hFigureMain,'labels',objLabels);

% update visualization
towers('menuVisualize_Callback', hFigureMain)

